apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: wiki-random
spec:
  schedule: "0 12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-random
            image: josephshih13/wiki-random
          restartPolicy: Never